### ISSUE TITLE
Trading package name

### ISSUE THREAD

**Issue by eljefedelrodeodeljefe** [dashed/probe#10]
Hi,
I am working on a ping and probing module and was wondering whether you'd be willing to trade in the nom module name.

Would be glad, and kind regards,

**Comment by dashed** [comment]
Howdy,

I wasn't clear on what you're asking; are you requesting to use the **probe** name: http://npm.im/probe? 

afaik, I don't manage nom: http://npm.im/nom

**Comment by eljefedelrodeodeljefe** [comment]
Yeah, the former. You manage http://npm.im/probe, right?

**Comment by dashed** [comment]
Sure I'd be happy to transfer the name (probe) to you. 

Before I do though, I'd just like for you to confirm that this is your user: https://www.npmjs.com/~eljefederodeodeljefe

**Comment by eljefedelrodeodeljefe** [comment]
Exactly. That's awesome @dashed

**Comment by dashed** [comment]
Done. 👍

**Comment by eljefedelrodeodeljefe** [comment]
Again thanks, and all the best!
